[package]
name = "browser-debloat"
edition = "2024"

[dependencies]
color-eyre = "0.6.4"
dirs = "6.0.0"
inquire = "0.7.5"
serde = { version = "1.0.219" }
serde_json = "1.0.140"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
